# Scraper work in progress

In [15]:
import requests
import pandas as pd
from datetime import datetime
from ratelimit import limits, sleep_and_retry

@sleep_and_retry
@limits(calls=10, period=10)
def call_api(url):
	print(f"Getting {url}")
	response = requests.get(url)
	parsed = response.json()
	return parsed

In [2]:
case_summaries_json = call_api('https://api.oyez.org/cases?per_page=0')

cases = []

for case_summary in case_summaries_json:
    df = pd.json_normalize(case_summary)
    cases.append(df)
    
cases_df = pd.concat(cases)
case_summary_df = cases_df[['ID','name','href','docket_number','term']].set_index('ID')
case_summary_df.to_csv('case_summary.csv', index=True)

In [ ]:
case_summary_df = pd.read_csv('case_summary.csv')

print("Case table ready: ",datetime.now())

recent_cases = case_summary_df[case_summary_df['term'] >= "2000"]

oa_list = []

for index, case in recent_cases.iterrows():
    case_json = call_api(case['href'])
    case_id = case_json['ID']
    if case_json['oral_argument_audio'] is not None:
    	oa = pd.json_normalize(case_json['oral_argument_audio'])[['id','title','href']].set_index('id')
   		#oa['date'] = oa['title'].apply(lambda L:L.split(' - ')[1])
    	oa['case_id'] = case_id
    	oa = oa[['case_id','title','href']]
    	oa_list.append(oa)

oa_df = pd.concat(oa_list)
oa_df.to_csv('oa_summary.csv', index=True)

In [18]:
oa_summary_df = pd.read_csv('oa_summary.csv')
oa_summary_df = oa_summary_df[oa_summary_df['title'] != 'No oral argument']

oa_summary_df.head()

,id,case_id,title,href
1,23122,54856,"Oral Argument - November 08, 2000",https://api.oyez.org/case_media/oral_argument_...
2,21358,54857,"Oral Argument - February 26, 2001",https://api.oyez.org/case_media/oral_argument_...
3,21837,54858,"Oral Argument - October 30, 2000",https://api.oyez.org/case_media/oral_argument_...
4,22771,54859,"Oral Argument - November 08, 2000",https://api.oyez.org/case_media/oral_argument_...
5,21446,54860,"Oral Argument - October 10, 2000",https://api.oyez.org/case_media/oral_argument_...

In [111]:
petitioner_transcripts = []

for index, oa in oa_summary_df.iterrows():
    oa_json = call_api(oa['href'])
    oa_id = oa_json['id']
    transcript = oa_json['transcript']
    petitioner_transcript = transcript['sections'][0]
    for index, turn in enumerate(petitioner_transcript['turns']):
        if turn['speaker'] is not None:
            speaker = turn['speaker']['ID']
        else:
            speaker = respondent_transcript['turns'][index - 2]['speaker']['ID']
        for speech in turn['text_blocks']:
            text = speech['text']
            start = speech['start']
            stop = speech['stop']
            pt_dict = {"oa_id":oa_id,"speaker_id":speaker,"start":start,"stop":stop,"text":text}
            petitioner_transcripts.append(pt_dict)

petitioner_transcript_df = pd.DataFrame(petitioner_transcripts)
            
respondent_transcripts = []

for index, oa in oa_summary_df.iterrows():
    oa_json = call_api(oa['href'])
    oa_id = oa_json['id']
    transcript = oa_json['transcript']
    respondent_transcript = transcript['sections'][1]
    for index, turn in enumerate(respondent_transcript['turns']):
        if turn['speaker'] is not None:
            speaker = turn['speaker']['ID']
        else:
            speaker = respondent_transcript['turns'][index - 2]['speaker']['ID']
        for speech in turn['text_blocks']:
            text = speech['text']
            start = speech['start']
            stop = speech['stop']
            pt_dict = {"oa_id":oa_id,"speaker_id":speaker,"start":start,"stop":stop,"text":text}
            respondent_transcripts.append(pt_dict)
        
respondent_transcript_df = pd.DataFrame(respondent_transcripts)
        
rebuttal_transcripts = []

for index, oa in oa_summary_df.iterrows():
    oa_json = call_api(oa['href'])
    oa_id = oa_json['id']
    transcript = oa_json['transcript']
    rebuttal_transcript = transcript['sections'][2]
    for index, turn in enumerate(rebuttal_transcript['turns']):
        if turn['speaker'] is not None:
            speaker = turn['speaker']['ID']
        else:
            speaker = respondent_transcript['turns'][index - 2]['speaker']['ID']
        for speech in turn['text_blocks']:
            text = speech['text']
            start = speech['start']
            stop = speech['stop']
            pt_dict = {"oa_id":oa_id,"speaker_id":speaker,"start":start,"stop":stop,"text":text}
            rebuttal_transcripts.append(pt_dict)
        
rebuttal_transcript_df = pd.DataFrame(rebuttal_transcripts)

Getting https://api.oyez.org/case_media/oral_argument_audio/23122
Getting https://api.oyez.org/case_media/oral_argument_audio/21358
Getting https://api.oyez.org/case_media/oral_argument_audio/21837
Getting https://api.oyez.org/case_media/oral_argument_audio/22771
Getting https://api.oyez.org/case_media/oral_argument_audio/21446
Getting https://api.oyez.org/case_media/oral_argument_audio/21985
Getting https://api.oyez.org/case_media/oral_argument_audio/22240

IndexError: list index out of range

In [114]:
test_transcript = call_api('https://api.oyez.org/case_media/oral_argument_audio/22240')['transcript']
for index, turn in enumerate(test_transcript['sections'][0]['turns']):
    if turn['speaker']['ID'] is not None:
        print(index, turn['speaker']['ID'])
    else:
        print(index, 'N/A')

#for turn in test_transcript['sections'][0]['turns']:
#    print(turn['speaker']['ID'], turn['speaker']['name'])

Getting https://api.oyez.org/case_media/oral_argument_audio/22240
0 15141
1 38302
2 15042
3 38302
4 15042
5 38302
6 15042
7 38302
8 15042
9 38302
10 15042
11 38302

TypeError: 'NoneType' object is not subscriptable

In [88]:
petitioner_transcripts = []

oa_json = call_api('https://api.oyez.org/case_media/oral_argument_audio/23122')
oa_id = oa_json['id']
transcript = oa_json['transcript']
petitioner_transcript = transcript['sections'][0]
for index, turn in enumerate(petitioner_transcript['turns']):
    if turn['speaker'] is not None:
        speaker = turn['speaker']['ID']
    else:
        speaker = petitioner_transcript['turns'][index - 2]['speaker']['ID']
        #should be person before, this turn is an interruption
    for speech in turn['text_blocks']:
        text = speech['text']
        start = speech['start']
        stop = speech['stop']
        pt_dict = {"oa_id":oa_id,"speaker_id":speaker,"start":start,"stop":stop,"text":text}
        petitioner_transcripts.append(pt_dict)

respondent_transcripts = []

oa_json = call_api('https://api.oyez.org/case_media/oral_argument_audio/23122')
oa_id = oa_json['id']
transcript = oa_json['transcript']
respondent_transcript = transcript['sections'][1]
for index, turn in enumerate(respondent_transcript['turns']):
    if turn['speaker'] is not None:
        speaker = turn['speaker']['ID']
    else:
        speaker = respondent_transcript['turns'][index - 2]['speaker']['ID']
    for speech in turn['text_blocks']:
        text = speech['text']
        start = speech['start']
        stop = speech['stop']
        pt_dict = {"oa_id":oa_id,"speaker_id":speaker,"start":start,"stop":stop,"text":text}
        respondent_transcripts.append(pt_dict)
        
respondent_transcript_df = pd.DataFrame(respondent_transcripts)
        
rebuttal_transcripts = []

oa_json = call_api('https://api.oyez.org/case_media/oral_argument_audio/23122')
oa_id = oa_json['id']
transcript = oa_json['transcript']
rebuttal_transcript = transcript['sections'][2]
for index, turn in enumerate(rebuttal_transcript['turns']):
    if turn['speaker'] is not None:
        speaker = turn['speaker']['ID']
    else:
        speaker = rebuttal_transcript['turns'][index - 2]['speaker']['ID']
    for speech in turn['text_blocks']:
        text = speech['text']
        start = speech['start']
        stop = speech['stop']
        pt_dict = {"oa_id":oa_id,"speaker_id":speaker,"start":start,"stop":stop,"text":text}
        rebuttal_transcripts.append(pt_dict)
        
rebuttal_transcript_df = pd.DataFrame(rebuttal_transcripts)

Getting https://api.oyez.org/case_media/oral_argument_audio/23122
Getting https://api.oyez.org/case_media/oral_argument_audio/23122
Getting https://api.oyez.org/case_media/oral_argument_audio/23122

,oa_id,speaker_id,start,stop,text
0,23122,33864,3399.859,3400.887,Thank you.
1,23122,33864,3400.887,3402.146,I think I have two points.
2,23122,33864,3402.146,3412.477,"Justice Breyer, as we understand the issue tha..."
3,23122,33864,3412.477,3441.359,The Court quoted the same provision of the sta...
4,23122,33864,3441.359,3455.325,And what the Court said in Haggar was that the...
5,23122,33864,3455.325,3462.487,I believe that... I want to say one more thing...
6,23122,33864,3462.487,3477.682,"Now, the cases that have described, that you l..."
7,23122,33864,3477.682,3505.865,"In Martin v. OSHRC, Occupational Safety & Heal..."
8,23122,33864,3505.865,3518.204,But in the context of the customs service ruli...
9,23122,15141,3518.204,3519.343,"Thank you, Mr. Jones."
10,23122,15141,3519.343,3520.577,The case is submitted.

To-do:
 
Table of speech  
Table of justices  
Table of advocates

# Ad-hoc

In [30]:
case = requests.get('https://api.oyez.org/cases/2019/18-1171')
case = case.json()

In [34]:
case.keys()

dict_keys(['ID', 'name', 'href', 'view_count', 'docket_number', 'additional_docket_numbers', 'manner_of_jurisdiction', 'first_party', 'second_party', 'timeline', 'lower_court', 'facts_of_the_case', 'question', 'conclusion', 'advocates', 'oral_argument_audio', 'citation', 'decisions', 'first_party_label', 'second_party_label', 'heard_by', 'decided_by', 'term', 'location', 'opinion_announcement', 'description', 'written_opinion', 'related_cases', 'justia_url', 'argument2_url'])

In [43]:
oa_df = pd.json_normalize(case['oral_argument_audio'])[['id','title','href']].set_index('id')
oa_df['date'] = oa_df['title'].apply(lambda L:L.split(' - ')[1])
oa_df = oa_df[['date','href']]
oa_df

                    date                                               href
id
25088  November 13, 2019  https://api.oyez.org/case_media/oral_argument_...

In [22]:
advocates = pd.json_normalize(case['advocates'])
advocates

,advocate_description,href,advocate.ID,advocate.name,advocate.href,advocate.view_count,advocate.last_name,advocate.roles,advocate.thumbnail,advocate.length_of_service,advocate.identifier
0,for the petitioner,https://api.oyez.org/case_advocate/case_advoca...,35754,Miguel A. Estrada,https://api.oyez.org/people/miguel_a_estrada,0,Estrada,None,None,0,miguel_a_estrada
1,"Assistant to the Solicitor General, Department...",https://api.oyez.org/case_advocate/case_advoca...,63108,Morgan L. Ratner,https://api.oyez.org/people/morgan_l_ratner,0,Ratner,None,None,0,morgan_l_ratner
2,for the respondents,https://api.oyez.org/case_advocate/case_advoca...,22098,Erwin Chemerinsky,https://api.oyez.org/people/erwin_chemerinsky,0,Chemerinsky,None,None,0,erwin_chemerinsky

In [27]:
#for index in range(len(case['oral_argument_audio'])):
#    print(case(['oral_argument_audio'])[index])
    
oa_1 = requests.get('https://api.oyez.org/case_media/oral_argument_audio/25088')

oa_1 = oa_1.json()

oa_1_df = pd.json_normalize(oa_1)
oa_1_df['date'] = oa_1_df['title'].apply(lambda L:L.split(' - ')[1])
oa_1_df['href'] = 'https://api.oyez.org/case_media/oral_argument_audio/25088'
oa_1_df[['id','date','href']]

      id               date                                               href
0  25088  November 13, 2019  https://api.oyez.org/case_media/oral_argument_...

In [ ]:
oa_1

In [9]:
oa_1_transcript = oa_1['transcript']
sections = oa_1_transcript['sections']
petitioner = sections[0]
respondent = sections[1]
petitioner_rebuttal = sections[2]

In [10]:
oa_1_transcript

{'title': 'COMCAST CORPORATION, Petitioner, v. NATIONAL ASSOCIATION OF AFRICAN AMERICAN-OWNED MEDIA, ET AL., Respondents',
 'duration': None,
 'sections': [{'start': 0.195,
   'stop': 1072.91,
   'byte_start': 0,
   'byte_stop': 0,
   'turns': [{'start': 0.195,
     'stop': 11.085,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15086,
      'name': 'John G. Roberts, Jr.',
      'href': 'https://api.oyez.org/people/john_g_roberts_jr',
      'view_count': 0,
      'last_name': 'Roberts',
      'roles': [{'id': 2730,
        'type': 'scotus_justice',
        'date_start': 1127970000,
        'date_end': 0,
        'appointing_president': 'George W. Bush',
        'role_title': 'Chief Justice of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2730'}],
      'thumbnail': {'id': 32683,
       'mime': 'image/png',
       'size': 52305,
       'href': 'https://api.oyez.org/sites/default/files/images/people/john_g_roberts_jr/john_g_roberts_jr.thumb.png'},
      'length_of_service': 5579,
      'identifier': 'john_g_roberts_jr'},
     'text_blocks': [{'start': 0.195,
       'stop': 11.085,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "We'll hear argument first this morning in Case 18-1171, Comcast Corporation versus the National Association of African American-Owned Media. Mr. Estrada."}]},
    {'start': 11.085,
     'stop': 141.205,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 11.085,
       'stop': 37.995,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "Mr. Chief Justice, and may it please the Court: The Ninth Circuit held in this case that a plaintiff may succeed on a Section 1981 claim merely by showing that race was a factor that was considered in the defendant's decision-making, even if the decision would have made and was made for entirely appropriate business reasons having nothing to do with race. Solely on this basis, the Ninth Circuit saved the Plaintiff's third complaint from dismissal."},
      {'start': 37.995,
       'stop': 121.08,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "We submit that this decision is wrong and should be reversed for at least three reasons. The first is that it is contrary to this Court's decisions, such as Gross and Nassar, holding that but-for causation is the background rule that Congress must have presumed to have been adopted in all federal statutes unless the statute provides otherwise, which we submit Section 1981 does not, either as originally adopted in 1866 or as amended in 1991. Second, in 1991, Congress amended Title VII to provide for a motivating factor standard but did not amend Section 1981 to provide the same, even though it amended Section 1981 in other respects at the same time. This all but conclusively shows that Section 1981 requires but-for causation, as this Court concluded in Gross and Nassar, with respect to the ADEA and the retaliation provisions of Title VII. And, third, it is -- if the Ninth Circuit is affirmed, it would be vastly easier to recover damages under Section 1981's judicially implied cause of action than under any express cause of action actually enacted by Congress under any federal antidiscrimination law."},
      {'start': 121.08,
       'stop': 141.205,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'And, thus, affirming the Ninth Circuit would effectively mean that Section 1981 would completely displace the carefully tailored regime that Congress has devised in Title VII to govern employment discrimination cases. No well-advised plaintiff would ever sue under Title VII in any employment case.'}]},
    {'start': 141.205,
     'stop': 195.35,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15086,
      'name': 'John G. Roberts, Jr.',
      'href': 'https://api.oyez.org/people/john_g_roberts_jr',
      'view_count': 0,
      'last_name': 'Roberts',
      'roles': [{'id': 2730,
        'type': 'scotus_justice',
        'date_start': 1127970000,
        'date_end': 0,
        'appointing_president': 'George W. Bush',
        'role_title': 'Chief Justice of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2730'}],
      'thumbnail': {'id': 32683,
       'mime': 'image/png',
       'size': 52305,
       'href': 'https://api.oyez.org/sites/default/files/images/people/john_g_roberts_jr/john_g_roberts_jr.thumb.png'},
      'length_of_service': 5579,
      'identifier': 'john_g_roberts_jr'},
     'text_blocks': [{'start': 141.205,
       'stop': 147.12,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "Counsel, it -- I -- I wonder if the distinction they're fighting over is -- is somewhat academic."},
      {'start': 147.12,
       'stop': 183.365,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "I -- in the contract negotiation process, for example, there may be several steps along the way, and if at one of those steps there's clear racial -- excuse me -- animus evident and that, you know, the process continues on, and at the end of the day, the contract is denied, it -- it may be hard to prove but-for causation. On the other hand, it's also hard to ignore the part -- the step in which there was clearly evident racial animus."},
      {'start': 183.365,
       'stop': 195.35,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'And it may be a reasonable argument or -- or -- excuse me -- allegation that that animus continued through, even though manifested only at one stage of the process.'}]},
    {'start': 195.35,
     'stop': 287.12,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 195.35,
       'stop': 235.575,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "Well, all complaints are different, Mr. Chief Justice, and I don't rule out, you know, the possibility that a complaint may allege such an expression of animus that it could actually imply that the animus continued until the end, such that it -- the complaint does allege but-for causation. Now the Plaintiffs, from the motion to dismiss in this case to the Ninth Circuit, have stuck their case on the proposition that they are alleging that race was a motivating factor and a motivating factor only, and they were not prepared to prove but-for causation -- causation. And, you know, we contend that that is wrong under Gross and Nassar."},
      {'start': 235.575,
       'stop': 287.12,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "Now we don't think that this complaint actually passes pleading standards under any standard, as we made clear, but, of course, you know, it is also the case that we have cases like Gross and Nassar in which it is evident from the record that some consideration of the protected factor was made in the employment context. And at the end, you know, the jury still had to be instructed that it had to determine whether that was a determinative factor in the decision-making. And in all of these cases, you know, the Court has already determined that the -- that the fact finder will have to make the decision, as -- as Gross said, whether that factor not only played a role but also had, as Justice Thomas put it in Gross, a determinative effect in the decision-making."}]},
    {'start': 287.12,
     'stop': 308.02,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15094,
      'name': 'Elena Kagan',
      'href': 'https://api.oyez.org/people/elena_kagan',
      'view_count': 0,
      'last_name': 'Kagan',
      'roles': [{'id': 2738,
        'type': 'scotus_justice',
        'date_start': 1281157200,
        'date_end': 0,
        'appointing_president': 'Barack Obama',
        'role_title': 'Associate Justice of the Supreme Court of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2738'}],
      'thumbnail': {'id': 32690,
       'mime': 'image/png',
       'size': 44456,
       'href': 'https://api.oyez.org/sites/default/files/images/people/elena_kagan/elena_kagan.thumb.png'},
      'length_of_service': 3806,
      'identifier': 'elena_kagan'},
     'text_blocks': [{'start': 287.12,
       'stop': 296.285,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "Mr. Estrada, you -- you said that the Respondents here continue to say that they don't have to prove but-for causation."},
      {'start': 296.285,
       'stop': 299.2,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "I'm a little bit confused about that point."},
      {'start': 299.2,
       'stop': 308.02,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'And I guess this is for Mr. Chemerinsky to think about as well. But, in your reply brief, you make the good point that on page 47 --'}]},
    {'start': 308.02,
     'stop': 308.16,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 308.02,
       'stop': 308.16,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'Forty-nine.'}]},
    {'start': 308.16,
     'stop': 309.41,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15094,
      'name': 'Elena Kagan',
      'href': 'https://api.oyez.org/people/elena_kagan',
      'view_count': 0,
      'last_name': 'Kagan',
      'roles': [{'id': 2738,
        'type': 'scotus_justice',
        'date_start': 1281157200,
        'date_end': 0,
        'appointing_president': 'Barack Obama',
        'role_title': 'Associate Justice of the Supreme Court of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2738'}],
      'thumbnail': {'id': 32690,
       'mime': 'image/png',
       'size': 44456,
       'href': 'https://api.oyez.org/sites/default/files/images/people/elena_kagan/elena_kagan.thumb.png'},
      'length_of_service': 3806,
      'identifier': 'elena_kagan'},
     'text_blocks': [{'start': 308.16,
       'stop': 309.41,
       'byte_start': 0,
       'byte_stop': 0,
       'text': '-- or 49 --'}]},
    {'start': 309.41,
     'stop': 310.395,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 309.41,
       'stop': 310.395,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'Right.'}]},
    {'start': 310.395,
     'stop': 317.3,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15094,
      'name': 'Elena Kagan',
      'href': 'https://api.oyez.org/people/elena_kagan',
      'view_count': 0,
      'last_name': 'Kagan',
      'roles': [{'id': 2738,
        'type': 'scotus_justice',
        'date_start': 1281157200,
        'date_end': 0,
        'appointing_president': 'Barack Obama',
        'role_title': 'Associate Justice of the Supreme Court of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2738'}],
      'thumbnail': {'id': 32690,
       'mime': 'image/png',
       'size': 44456,
       'href': 'https://api.oyez.org/sites/default/files/images/people/elena_kagan/elena_kagan.thumb.png'},
      'length_of_service': 3806,
      'identifier': 'elena_kagan'},
     'text_blocks': [{'start': 310.395,
       'stop': 313.745,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "-- of the Respondents' brief, they seem to say the opposite."},
      {'start': 313.745,
       'stop': 317.3,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'They seem to suggest by quoting that Third Circuit case --'}]},
    {'start': 317.3,
     'stop': 318.17,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 317.3,
       'stop': 318.17,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'The Kaz case, right.'}]},
    {'start': 318.17,
     'stop': 329.49,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15094,
      'name': 'Elena Kagan',
      'href': 'https://api.oyez.org/people/elena_kagan',
      'view_count': 0,
      'last_name': 'Kagan',
      'roles': [{'id': 2738,
        'type': 'scotus_justice',
        'date_start': 1281157200,
        'date_end': 0,
        'appointing_president': 'Barack Obama',
        'role_title': 'Associate Justice of the Supreme Court of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2738'}],
      'thumbnail': {'id': 32690,
       'mime': 'image/png',
       'size': 44456,
       'href': 'https://api.oyez.org/sites/default/files/images/people/elena_kagan/elena_kagan.thumb.png'},
      'length_of_service': 3806,
      'identifier': 'elena_kagan'},
     'text_blocks': [{'start': 318.17,
       'stop': 323.61,
       'byte_start': 0,
       'byte_stop': 0,
       'text': '-- that, in fact, they are going to have to prove but-for causation at the end.'},
      {'start': 323.61,
       'stop': 329.49,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'And the question here is really what they have to allege now.'}]},
    {'start': 329.49,
     'stop': 329.985,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 329.49,
       'stop': 329.985,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'I --'}]},
    {'start': 329.985,
     'stop': 367.405,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15094,
      'name': 'Elena Kagan',
      'href': 'https://api.oyez.org/people/elena_kagan',
      'view_count': 0,
      'last_name': 'Kagan',
      'roles': [{'id': 2738,
        'type': 'scotus_justice',
        'date_start': 1281157200,
        'date_end': 0,
        'appointing_president': 'Barack Obama',
        'role_title': 'Associate Justice of the Supreme Court of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2738'}],
      'thumbnail': {'id': 32690,
       'mime': 'image/png',
       'size': 44456,
       'href': 'https://api.oyez.org/sites/default/files/images/people/elena_kagan/elena_kagan.thumb.png'},
      'length_of_service': 3806,
      'identifier': 'elena_kagan'},
     'text_blocks': [{'start': 329.985,
       'stop': 350.13,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "And if -- if -- if -- if we take it that way, I mean, Mr. Chemerinsky can say what he wants to say about that, but let's just assume that that's true, that they are going to have to plead but-for -- excuse me, that they're going to have to prove but-for causation at the end; that is the ultimate standard in the case. But this is a complaint."},
      {'start': 350.13,
       'stop': 367.405,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "And, you know, it's pre-discovery and the Plaintiff is not going to know what the Defendant was thinking about in making whatever contract decisions the Defendant was making. And -- and -- and so what do you think the Plaintiff has to allege at the beginning?"}]},
    {'start': 367.405,
     'stop': 385.82,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 367.405,
       'stop': 371.14,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'Well, I think -- you know, I have two answers to that.'},
      {'start': 371.14,
       'stop': 379.27,
       'byte_start': 0,
       'byte_stop': 0,
       'text': "I think, first, the Ninth Circuit's ruling in this case had nothing to say about the difference between pleading and the merits."},
      {'start': 379.27,
       'stop': 385.82,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'In fact, the Ninth Circuit worked from what was needed to prevail on the merits to then upholding the complaint.'}]},
    {'start': 385.82,
     'stop': 398.06,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 15094,
      'name': 'Elena Kagan',
      'href': 'https://api.oyez.org/people/elena_kagan',
      'view_count': 0,
      'last_name': 'Kagan',
      'roles': [{'id': 2738,
        'type': 'scotus_justice',
        'date_start': 1281157200,
        'date_end': 0,
        'appointing_president': 'Barack Obama',
        'role_title': 'Associate Justice of the Supreme Court of the United States',
        'institution_name': 'Supreme Court of the United States',
        'href': 'https://api.oyez.org/preson_role/scotus_justice/2738'}],
      'thumbnail': {'id': 32690,
       'mime': 'image/png',
       'size': 44456,
       'href': 'https://api.oyez.org/sites/default/files/images/people/elena_kagan/elena_kagan.thumb.png'},
      'length_of_service': 3806,
      'identifier': 'elena_kagan'},
     'text_blocks': [{'start': 385.82,
       'stop': 398.06,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'Yeah, so I take that point, and I would think that if -- if my assumption holds, which is that the Respondents do have to prove this at the end, then you would have to say that the Ninth Circuit is wrong. But you would still have --'}]},
    {'start': 398.06,
     'stop': 398.59,
     'byte_start': 0,
     'byte_stop': 0,
     'speaker': {'ID': 35754,
      'name': 'Miguel A. Estrada',
      'href': 'https://api.oyez.org/people/miguel_a_estrada',
      'view_count': 0,
      'last_name': 'Estrada',
      'roles': None,
      'thumbnail': None,
      'length_of_service': 0,
      'identifier': 'miguel_a_estrada'},
     'text_blocks': [{'start': 398.06,
       'stop': 398.59,
       'byte_start': 0,
       'byte_stop': 0,
       'text': 'That would not be novel.'}]},
    {'start': 398.59,
     'stop': 400.85,
     'byte_start': 0,

In [11]:
section_1_turn_1 = petitioner['turns'][0]
speaker_name = section_1_turn_1['speaker']['name']
text_blocks = section_1_turn_1['text_blocks']
text_block_1 = text_blocks[0]

n_words_spoken = len(text_block_1['text'])

text = text_block_1['text']

n_times_address_counsel = text.count('Counsel') + text.count('counsel')

print(speaker_name,':', n_words_spoken, 'words spoken.', n_times_address_counsel, 'times addressing counsel.')

John G. Roberts, Jr. : 153 words spoken. 0 times addressing counsel.